name: CategoryConstructor
version: "2022.02-09"
license: "GPL-2.0-or-later"
date: 2022-02-13
description: |
    Construct categories out of given ones

authors:
    - name: Mohamed Barakat
      url: https://mohamed-barakat.github.io/

maintainers:
    - name: Mohamed Barakat
      url: https://mohamed-barakat.github.io/

GAP: ">= 4.9.1"

needed-pkgs:
    - name: "GAPDoc"
      version: ">= 1.5"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"
    - name: "CAP"
      version: ">= 2021.08-03"
      url: "https://homalg-project.github.io/pkg/CAP"
    - name: "MonoidalCategories"
      version: ">= 2022.02-08"
      url: "https://homalg-project.github.io/pkg/MonoidalCategories"
    - name: "ToolsForHomalg"
      version: ">= 2021.11-01"
      url: "https://homalg-project.github.io/pkg/ToolsForHomalg"

suggested-pkgs:
    - name: "IO_ForHomalg"
      version: ">= 2019.01.01"
      url: "https://homalg-project.github.io/pkg/IO_ForHomalg"

www: https://homalg-project.github.io/pkg/CategoryConstructor
readme: README.md
packageinfo: https://homalg-project.github.io/CategoryConstructor/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/homalg-project/CategoryConstructor/releases/download/v2022.02-09/CategoryConstructor-2022.02-09.tar.gz
    - name: .zip
      url: https://github.com/homalg-project/CategoryConstructor/releases/download/v2022.02-09/CategoryConstructor-2022.02-09.zip

pdf: https://github.com/homalg-project/CategoryConstructor/releases/download/v2022.02-09/CategoryConstructor-2022.02-09.pdf

abstract: |

status: dev
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
keywords: |
    Category constructor.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>Bar22</span>]   <b class='BibAuthor'>Barakat, M.</b>,
     <i class='BibTitle'>CategoryConstructor, Construct categories out of given ones,
             Version 2022.02-09</i>
     (<span class='BibYear'>2022</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://homalg-project.github.io/pkg/CategoryConstructor">https://homalg-project.github.io/pkg/CategoryConstructor</a></span>.
    </p>
    

bibtex: |
    @misc{ CategoryConstructor2022.02-09,
      author =           {Barakat, M.},
      title =            {{CategoryConstructor},  Construct  categories  out  of
                          given ones, {V}ersion 2022.02-09},
      month =            {Feb},
      year =             {2022},
      note =             {GAP package},
      howpublished =     {\href
                          {https://homalg-project.github.io/pkg/CategoryConstructor}
                          {\texttt{https://homalg-project.github.io/}\discretionary
                          {}{}{}\texttt{pkg/}\discretionary
                          {}{}{}\texttt{CategoryConstructor}}},
      keywords =         {Category constructor},
      printedkey =       {Bar22}
    }

