name: CategoryConstructor
version: "2022.11-11"
license: "GPL-2.0-or-later"
date: 2022-11-29
description: |
    Construct categories out of given ones

authors:
    - name: Mohamed Barakat
      url: https://mohamed-barakat.github.io/

maintainers:
    - name: Mohamed Barakat
      url: https://mohamed-barakat.github.io/

GAP: ">= 4.11.1"

needed-pkgs:
    - name: "CAP"
      version: ">= 2022.11-27"
      url: "https://homalg-project.github.io/pkg/CAP"
    - name: "MonoidalCategories"
      version: ">= 2022.06-03"
      url: "https://homalg-project.github.io/pkg/MonoidalCategories"
    - name: "ToolsForHomalg"
      version: ">= 2021.11-01"
      url: "https://homalg-project.github.io/pkg/ToolsForHomalg"

www: https://homalg-project.github.io/pkg/CategoryConstructor
readme: README.md
packageinfo: https://homalg-project.github.io/CategoryConstructor/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/homalg-project/CategoryConstructor/releases/download/v2022.11-11/CategoryConstructor-2022.11-11.tar.gz
    - name: .zip
      url: https://github.com/homalg-project/CategoryConstructor/releases/download/v2022.11-11/CategoryConstructor-2022.11-11.zip

pdf: https://github.com/homalg-project/CategoryConstructor/releases/download/v2022.11-11/CategoryConstructor-2022.11-11.pdf

abstract: |

status: dev
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
keywords: |
    Category constructor.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>Bar22</span>]   <b class='BibAuthor'>Barakat, M.</b>,
     <i class='BibTitle'>CategoryConstructor, Construct categories out of given ones,
             Version 2022.11-11</i>
     (<span class='BibYear'>2022</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://homalg-project.github.io/pkg/CategoryConstructor">https://homalg-project.github.io/pkg/CategoryConstructor</a></span>.
    </p>
    

bibtex: |
    @misc{ CategoryConstructor2022.11-11,
      author =           {Barakat, M.},
      title =            {{CategoryConstructor},  Construct  categories  out  of
                          given ones, {V}ersion 2022.11-11},
      month =            {Nov},
      year =             {2022},
      note =             {GAP package},
      howpublished =     {\href
                          {https://homalg-project.github.io/pkg/CategoryConstructor}
                          {\texttt{https://homalg-project.github.io/}\discretionary
                          {}{}{}\texttt{pkg/}\discretionary
                          {}{}{}\texttt{CategoryConstructor}}},
      keywords =         {Category constructor},
      printedkey =       {Bar22}
    }

